# Generated by Django 4.2.13 on 2024-05-10 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JeuDeDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MethodeCompression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('taux_compression', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('parametres_compression', models.TextField()),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModeleCompresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapport', models.TextField()),
                ('metrics', models.TextField()),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('resultats', models.TextField()),
                ('jeux_de_donnees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.jeudedonnees')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.modele')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.TextField()),
                ('resultat_compression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.modelecompresse')),
            ],
        ),
        migrations.AddField(
            model_name='modelecompresse',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.tache'),
        ),
        migrations.AddField(
            model_name='modele',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.utilisateur'),
        ),
        migrations.CreateModel(
            name='MetriqueCompression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.tache')),
            ],
        ),
    ]
