# Generated by Django 4.2.13 on 2024-05-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JeuDeDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MethodeCompression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetriqueCompression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetriqueEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('path', models.CharField(max_length=255)),
                ('jeu_de_donnees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.jeudedonnees')),
            ],
        ),
        migrations.CreateModel(
            name='ModeleCompresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.modele')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=255)),
                ('taux_compression', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('finished', models.BooleanField(default=False)),
                ('jeux_de_donnees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.jeudedonnees')),
                ('methode_compression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.methodecompression')),
                ('metrique_compression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.metriquecompression')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.modele')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('metrique_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.metriqueevaluation')),
                ('modele_compresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.modelecompresse')),
            ],
        ),
        migrations.AddField(
            model_name='modelecompresse',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compression_app.tache'),
        ),
    ]
